travis:
  secure:
    BINSTAR_TOKEN: tlNkpgU6wgk7+nnbJPh8z2kwt4HvGqchZJmPxwgJr0rh+mLnTw8V1HTTazfLyryk37/C6rKImd5FfBao1L4uvtdavsbhm0q5BaWLN+B2prBbxeosxRr1yb0yqn5hR68YwHIUCEiHD6XFgeSJzk1g6T1kQf0zcvTku5vZRYM70enkefaClR0ekrTnNn44MIiVPiffNI18JjY+27BDClScZLAUzJ501rmVGBewOqJ6cRY9Tpy+hM1kyScB/xbf5AH4Icfcz8QfSwcPf9RQicr/ZPsmZElVxhvCdeKlF79B81oEBVULmvnQOXQDQTXkCZuwDZAIjZoiG1ZcHUHd9EzDQmVwvcyC6IJYRGO2iUMo22tQew2WqgDhFRHKYQaX+BpPnygIWcfnh8CZHZRW9ZFV6AFIrrgHwCLmzb6eSyWq+4F6VPYnbc0lbodN6NEL0M5AmOpPbz17HOy0vhHzO9FBAWfkLe2Xipz2tWLtPnVrMnIWd8Yj8ka4OEDHRWio34VcxzwAkQtKquUi+iRE/5NzTraAlrqksoY40Gk6RphHH7qy6igGPMiPtfiBkZtN9hpaFHg2nzqtFUhzsI3r1Rx6WAVVn47yyKD+9pbUwbs9WFBLwlw/bQpj/GPc14FOYzcaLzwcUOC+A1ol7VKLdfHVRk02egiWd3WgIPHuZc6B6OE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
